#!/usr/bin/env python
import sys, os
from pathlib import Path

if len(sys.argv) != 2:
  print(f"Usage: {sys.argv[0]} <filename/directory>")
  exit()
# ~~
tmp=sys.argv[1].rstrip("/")
files=[]
if os.path.isdir(tmp): # or tmp=="." or tmp=="..":
  for file in Path(tmp).rglob("*"): # recursively glob
    if file.is_file():
      files.append(file)
else:
  files.append(tmp)

for filename in files:
  with open(filename, 'r', encoding='utf-8') as file:
    for line_number, line in enumerate(file, start=1):
      lineB=line.rstrip('\n')
      if lineB.rstrip() != lineB:  # Check if trailing whitespace exists
        print(f"{filename}: Line {line_number}: {repr(line)}")
