#!/usr/bin/env python
# POC: Guoqing.Ge@noaa.gov
#
import sys, os
from pathlib import Path

if len(sys.argv) != 2:
  print(f"Usage: {sys.argv[0]} <filename/directory>")
  exit()
# ~~
tmp=sys.argv[1].rstrip("/")
files=[]
if os.path.isdir(tmp): # or tmp=="." or tmp=="..":
  for file in Path(tmp).rglob("*"): # recursively glob
    if file.is_file():
      files.append(file)
else:
  files.append(tmp)

for filename in files:
  with open(filename, 'r', encoding='utf-8') as infile, open(f'.tmp.{filename}','w',encoding='utf-8') as outfile:
    for line in infile:
      outfile.write(line.rstrip()+'\n')
  os.replace(f'.tmp.{filename}',filename)
