#!/usr/bin/env python
# POC: Guoqing.Ge@noaa.gov
#
import yaml, sys, os
from datetime import datetime

# Custom Dumper class to modify list formatting
class MyDumper(yaml.Dumper):
  def represent_datetime(self,data):
    return self.represent_scalar('tag:yaml.org,2002:timestamp', data.strftime('%Y-%m-%dT%H:%M:%SZ'))
  def represent_list(self, data):
    # Check if the list contains only simple literals (strings, numbers, booleans)
    if all(isinstance(item, (str, int, float, bool)) for item in data):
      # Use compact flow style ([])
      return self.represent_sequence('tag:yaml.org,2002:seq', data, flow_style=True)
    else:
      # Use block style (-)
      return self.represent_sequence('tag:yaml.org,2002:seq', data, flow_style=False)

# ====== main =========
MyDumper.add_representer(list, MyDumper.represent_list)
MyDumper.add_representer(datetime, MyDumper.represent_datetime)

args=sys.argv
nargs=len(args)-1
if nargs <1:
  print(f"jquery <yamlfile_name>")
  exit()

yfile=open(args[1], 'r')
data=yaml.safe_load(yfile)

# create a subdirectory 'break_yaml'
os.makedirs('./break_yaml',exist_ok=True)
os.chdir('./break_yaml')

# dump the output and variational sections to variational.yaml
tmp={
  'output': data['output'],
  'variational': data['variational']
  }
with open('variational.yaml','w') as outfile:
  yaml.dump(tmp, outfile, Dumper=MyDumper, default_flow_style=False, sort_keys=False)

# get the "cost function" sub dictionary and dump header contents except "background erro" and "observations" keys
costf=data['cost function']
tmp={
  'cost type': costf['cost type'],
  'time window': costf['time window'],
  'jb evaluation': costf['jb evaluation'],
  'geometry': costf['geometry'],
  'analysis variables': costf['analysis variables'],
  'background': costf['background']
    }
with open('costf_header.yaml','w') as outfile:
  yaml.dump(tmp, outfile, Dumper=MyDumper, default_flow_style=False, sort_keys=False)

# dump 'background error'
components=[]
BEC=costf['background error']
if BEC['covariance model'].upper() == "HYBRID":
  components=BEC['components']
else:
  comp={'covariance': BEC, 'weight':{'value':1.0}}
  components.append(comp)
for index,mybec in enumerate(components):
  cov=mybec['covariance']
  wgt=mybec['weight']['value']
  fname=f"costf_bec{index}_{cov['covariance model']}_wgt{wgt}.yaml"
  with open(fname,'w') as outfile:
    yaml.dump(cov, outfile, Dumper=MyDumper, default_flow_style=False, sort_keys=False)

# summarize the assimilated observation types and dump observations to break_yaml/obs
os.makedirs('./obs',exist_ok=True)
obslist=costf['observations']['observers']
nobs=len(obslist)
obs_text=''
filter_text=''
for i in range(nobs):
  lname=obslist[i]['obs space']['name']
  sname=lname.split('=')[0]
  obs_text=obs_text+sname+','
  os.makedirs(f'./obs/{i:02}_{sname}',exist_ok=True)
  #
  # get the observations headers (excluding the filters) and dump
  observer={
    'obs space': obslist[i]['obs space'],
    'obs operator': obslist[i]['obs operator'],
    'obs localizations': obslist[i]['obs localizations']
      }
  if 'obs error' in obslist[i]: # radiance data does not have the 'obs error' section
    observer['obs error']=obslist[i]['obs error']

  if 'obs bias' in obslist[i]:
    with open(f'obs/{i:02}_{sname}/bias.yaml','w') as outfile:
      yaml.dump(obslist[i]['obs bias'], outfile, Dumper=MyDumper, default_flow_style=False, sort_keys=False)

  with open(f'obs/{i:02}_{sname}/header.yaml','w') as outfile:
    yaml.dump(observer, outfile, Dumper=MyDumper, default_flow_style=False, sort_keys=False)
  # dealing with filters
  filter_text=filter_text+f'\n#[{lname}]:\n'
  if 'obs pre filters' in obslist[i]:
    for j,value in enumerate(obslist[i]['obs pre filters']):
      myfilter=value['filter']
      if myfilter == 'Perform Action':
        myfilter=value['action']['name']
      filter_text=filter_text+f' {myfilter},'
      myfilter=myfilter.replace(' ', '_')
      with open(f'obs/{i:02}_{sname}/prefilter{j:02}_{myfilter}.yaml','w') as outfile:
        yaml.dump(value, outfile, Dumper=MyDumper, default_flow_style=False, sort_keys=False)
  #
  if 'obs filters' in obslist[i]:
    for j,value in enumerate(obslist[i]['obs filters']):
      myfilter=value['filter']
      if myfilter == 'Perform Action':
        myfilter=value['action']['name']
      filter_text=filter_text+f' {myfilter},'
      myfilter=myfilter.replace(' ', '_')
      with open(f'obs/{i:02}_{sname}/filter{j:02}_{myfilter}.yaml','w') as outfile:
        yaml.dump(value, outfile, Dumper=MyDumper, default_flow_style=False, sort_keys=False)
  #
  if 'obs post filters' in obslist[i]:
    for j,value in enumerate(obslist[i]['obs post filters']):
      myfilter=value['filter']
      if myfilter == 'Perform Action':
        myfilter=value['action']['name']
      filter_text=filter_text+f' {myfilter},'
      myfilter=myfilter.replace(' ', '_')
      with open(f'obs/{i:02}_{sname}/postfilter{j:02}_{myfilter}.yaml','w') as outfile:
        yaml.dump(value, outfile, Dumper=MyDumper, default_flow_style=False, sort_keys=False)
  #
  filter_text=filter_text.rstrip(',')+'\n'
#
obs_text=f'{nobs} observers:\n{obs_text.rstrip(",")}'
print(obs_text)
with open('summary_obs.log','w') as outfile:
  outfile.write(f'{obs_text}\n\n{filter_text}\n')
#

# print out information
print("\nbreakout yaml files generated under ./break_yaml/")
